// <auto-generated />
namespace WindowsFormsApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class NewMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202505030740226_NewMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
